using Test
using Physis

include("test_symbols.jl")
include("test_rules.jl")
include("test_rewriter.jl")
include("test_context.jl")
include("test_turtle2d.jl")
include("test_turtle3d.jl")
include("test_render_api.jl")
include("test_cairomakie_ext.jl")
include("test_geometry.jl")
include("test_gltf.jl")
include("test_species.jl")
include("test_blender.jl")
include("test_gallery.jl")
include("test_leaf_geometry.jl")
include("test_flower_geometry.jl")
include("test_organ_placement.jl")
include("test_pipe_model.jl")
include("test_phyllotaxis.jl")
include("test_tropisms.jl")
include("test_space_colonization.jl")
include("test_weber_penn.jl")
include("test_self_organizing.jl")
include("test_species_coniferous.jl")
include("test_species_ferns.jl")
include("test_species_tropical.jl")
include("test_species_flowers.jl")
include("test_species_grasses.jl")
include("test_species_succulents.jl")
include("test_species_aquatic.jl")
include("test_species_vines.jl")
include("test_species_shrubs.jl")
include("test_animation.jl")
include("test_lod.jl")
